name: Test
concurrency: production

on:
  push:
    branches: [ test_e2e ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
      
      - name: ⚙️ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest

      - name: Display test results
        if: failure() # This step runs only if the tests fail
        run: cat ./test-results.txt || echo "No test results file found"
      
      - name: Start the server
        run: npm start &
        env:
          NODE_ENV: test
          
      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:3030

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e