name: Test
concurrency: test-${{ github.ref }}

on:
  push:
    branches: [ test_e2e ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:unit
        env:
          CI: true

      - name: Collect Jest results
        if: always()
        run: cat ./reports/jest/jest-results.xml || echo "No Jest results found"
        id: jest_summary

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Collect Playwright results
        if: always()
        run: cat ./reports/playwright/playwright-results.xml || echo "No Playwright results found"
        id: playwright_summary

      - name: Generate Summary
        if: always() 
